Docstrings for plotting.py
tobac-project/tobac pull request #155
Opened 2022-07-06 15:57 UTC by snilsn

This PR contains revised docstrings for the plotting.py functions I've gotten to work so far.

Unfortunately, this time there are more functions which are not covered yet. To keep track of that I use this [table](https://docs.google.com/spreadsheets/d/1dD7TFlRgcMKWeh0NkHuj24O6guvbEdTrm0x2eCOMtnM/edit#gid=1309608279)

I created a [notebook](https://github.com/snilsn/tobac_functions/blob/master/plotting_functions.ipynb) of my experiments with the functions that are marked as 'broken?'. I suspect some of them to have bugs, maybe resulting from changes in other parts of tobac. Others I perhaps use in the wrong way. None of these I saw in use in any of the examples.

This is probably worth a separate issue, like suggested in #146. We should discuss whether they should still be included in this PR.

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you formatted your code using black? 
* [x] Have all tests passed in your local clone? 
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged? 

Not needed:

* [ ] Have you added NumPy docstrings for newly added functions?
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [ ] If you have introduced a new functionality, have you added an example notebook?

2022-07-06 22:08 UTC, freemansw1 commented
Thanks Nils! I've requested @JuliaKukulies and myself for review. I'll try to get this reviewed before the developers' meeting. Agreed that we should discuss the plotting.py functions; I had no idea that this many of them were broken. I'm happy for you to open the issue, or I can do that!

2022-07-07 11:07 UTC, JuliaKukulies requested changes
Thank you @snilsn for these comprehensive documentation improvements! This was for sure not an easy task, and based on your notebooks it seems like the plotting functions need some general revisions, which probably will require some update of these docstrings at a later point. I would, however, be happy to get these changes in for v1.4 as these are a nice complement to your PR #138. Again, just a few comments and suggestions, mainly typos and some clarifications

2022-07-08 08:39 UTC, snilsn commented on tobac/plotting.py
> +Plotting routines including both visualizations of the entire cloud field
Yes, that is what is meant. I'll reword that, also to avoid the word cloud again, I missed that.

2022-07-08 08:51 UTC, snilsn commented on tobac/plotting.py
> +        One ore more framesof the output of linking_trackpy.
Yes, I rephrased that.

2022-07-08 09:17 UTC, snilsn commented on tobac/plotting.py
> +    track
Probably, but not sure about that. It doesn't work out of the box with the tracks I created from the testing-datasets in my notebook.

2022-07-08 09:21 UTC, snilsn commented on tobac/plotting.py
> +    cog
This was the first function I encountered that didn't work, but I already started writing the docstring. Probably shouldn't have included that in the PR :) 
Will remove.

2022-07-08 09:37 UTC, snilsn commented on tobac/plotting.py
> +    bin_edges : int or ndarray, optional
Oh not in that case apparently. Sometimes it has a default value and sometimes it doesn't, misssed that.

2022-07-08 09:45 UTC, snilsn commented
Thanks for your feedback, @JuliaKukulies, most of your suggestions should be covered by the last commit.

2022-07-08 12:43 UTC, JuliaKukulies approved these changes
All right, approved from my side! Thanks for the changes @snilsn 

I guess we can see over that codecov fails here - maybe discuss later how to set the threshold for accepted decrease in coverage.

2022-07-08 12:43 UTC, JuliaKukulies commented on tobac/plotting.py
> +    Output:
For this function, you reversed the docstring changes. Just checking if this was intentionally?

2022-07-08 12:52 UTC, JuliaKukulies commented on tobac/plotting.py
> +    onto individual maps for all timeframes and
OK, you are right. So maybe add it there? I think it is useful to know from the description, even though you can see that if or not a filename is one of the input parameters.

2022-07-09 17:02 UTC, freemansw1 approved these changes
Just a minor comment. Great work again.

2022-07-09 17:19 UTC, freemansw1 commented
OK- I've opened a new issue for the broken functions (#158).

2022-07-10 19:49 UTC, snilsn commented on tobac/plotting.py
> +        GeoAxesSubplot to use for plotting. Default is None.
Yes, true, going to add that.

2022-07-11 07:05 UTC, snilsn commented on tobac/plotting.py
> +        GeoAxesSubplot to use for plotting. Default is None.
Added it to the other keyword arguments that aren't actually optional in the function description and removed the 'optional'. But this feels like bad style, maybe we should delete the default values in the code for these kwargs? There should be no working code including this function without passing them anyway.

2022-07-11 14:58 UTC, freemansw1 commented on tobac/plotting.py
> +        GeoAxesSubplot to use for plotting. Default is None.
Yes, generally I agree with you that this is bad style. However, given our prior experience with needing to depreciate a positional argument (#125), I'm disinclined from moving a kwarg to a positional arg without a lot of discussion. I think that given the discussion in #158, we will put this on hold for now until we ultimately decide what to do with the functions.

2022-07-11 14:59 UTC, freemansw1 commented
Now that we have two approvals and this is passing non-coverage tests (see #159), I'm happy to merge this if you are happy for it to be merged @snilsn .

2022-07-11 15:20 UTC, snilsn commented on tobac/plotting.py
> +        GeoAxesSubplot to use for plotting. Default is None.
Oh yes, forgot about that. I agree to put this on hold for now.

2022-07-11 15:21 UTC, snilsn commented
Yes all good, please go ahead @freemansw1

2022-07-11 15:22 UTC, merged