Deprecate Python 3.6 and lower support
tobac-project/tobac pull request #193
Opened 2022-10-24 03:06 UTC by freemansw1

Resolves the first half of #185. Rather than dropping support for <3.7, I'm proposing that we only deprecate it in the code. We will still tell conda-forge that we require >=3.7, but this allows users who must remain on old versions to stick around for now. We will drop support with v1.5, as I'd really like to start adding typing annotations. 

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [ ] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

2022-10-24 10:23 UTC, JuliaKukulies requested changes
I agree with your comment on type annotations for `v1.5` and I like your suggestion to first deprecate older python versions instead of directly dropping the support @freemansw1! 

However, I am not sure what the best way to do this is. I tested to install `tobac` with Python 3.6 and even though your code works perfectly fine when run outside of `setup.py`, the `DeprecationWarning` does neither show up when installing `tobac` from the local clone (`pip install tobac/`) nor when `tobac` is installed using `conda`. 

For Python versions > 3.7, the `DeprecationWarning` shows up when using the verbose flag: `pip install -v tobac/`, but this does not really help us, because obviously the warning is only raised for older versions and even when it shows up it is a bit difficult to read with all the other output `setup.py` gives.

I am trying to find out what others have done. Maybe just state in the `README`? 

Also, do I understand it correctly that you propose to already now require `>3.7` for `conda `so that users who install `tobac v1.4.0` via `conda` would need to do so with Python >3.7 while users who need to remain with older Python versions need to install `tobac v1.4.0` from the github repo?

2022-10-24 12:40 UTC, JuliaKukulies commented
OK, I tried some things and what worked is to use a print statement and put it at the end of `setup.py` and add some blank lines so that it sticks out from the other output. This does, however, also only work when installing `tobac` from source with `python -v install .` My suggestion would be to just add it here but also write the same to the `README` because most users probably do not use the `verbose flag`. 

```python 

if sys.version_info[0] < 3.7:
    warning = """ \n\n 
    Support for Python versions less than 3.7 is deprecated. 
    Version 1.5 of tobac will require Python 3.7 or later.
   Python {py} detected. \n\n
    """.format(py='.'.join(str(v) for v in sys.version_info[:3]))

    print(warning)  
```

2022-10-24 15:13 UTC, freemansw1 commented
> Also, do I understand it correctly that you propose to already now require >3.7 for conda so that users who install tobac v1.4.0 via conda would need to do so with Python >3.7 while users who need to remain with older Python versions need to install tobac v1.4.0 from the github repo?

Yes, that's my proposal. I think that will happen anyway, even without our explicit doing, due to the fact that conda-forge doesn't support 3.7 or lower anymore. If a user needs to be on Python <3.6, they can still get `tobac` for now, but it's now 6 years old, so I am not opposed to nudging users to upgrade sooner rather than later.

2022-10-24 15:25 UTC, JuliaKukulies approved these changes
Thanks for these changes @freemansw1! That was a good idea to switch the warning to import instead. I also tested it one more time in a python 3.6 environment and it works fine.

2022-10-24 15:41 UTC, JuliaKukulies commented
And good point with #176. I am almost inclined to say that we are OK with it due to the reasons that you mention (better sooner than later nudge users to upgrade and users installing `tobac` from now with  `conda-forge` with python<3.4 will get `tobac1.2` anyhow). I would think that a smooth transition from Python3.6 is more important because this probably concerns much more people, but if others have a different opinion, we can definitely work out a PR that still supports Python 2 for the new release. In #176 this only concerns the `pathlib` module, right? Note that we also used it in the updated examples (#186).

2022-10-25 09:26 UTC, snilsn approved these changes
Good work, @freemansw1, I didn't find any issues. Giving a warning on import is probably the best way to do this, since it's a more frequent reminder.

2022-10-25 14:50 UTC, freemansw1 commented
Thanks! 

Agreed with you @JuliaKukulies . If users are still on Python 2.7 or <3.4, they can use tobac v1.3.3. If they're on those python versions, they must be installing from GitHub anyway as conda-forge doesn't support those versions.

2022-10-25 14:50 UTC, merged