Add option to define different n_min_threshold dependent on thresholds
tobac-project/tobac pull request #208
Opened 2022-12-01 13:05 UTC by JuliaKukulies

This PR solves #18 by allowing users to input `n_min_threshold` (the minimum number of grid cells that must be above/below the set threshold(s))  as `dict` or `list`. That way, different `n_min_threshold` values are used for different threshold values in the feature detection. 

The code changes encompass: 

- Changes to the function `feature_detection_multithreshold_timestep()` because here, individual threshold values are selected and passed to `feature_detection_threshold()`
- Input validation to make sure that each threshold is assigned to one `n_min_threshold`.  This means that the number of elements of the given `dict` or `list` has to be the same as the number of given thresholds. It is also made sure that these values are sorted accordingly when threshold values are sorted. When `n_min_threshold` is given as `dict`, the keys must correspond to the threshold values. When `n_min_threshold` is given as `list`, it is assumed that each `n_min_threshold` belongs to the value in `threshold` at the same position. 
- Additional test parameters in  `test_feature_detection.py` to test the new feature
- Modifications to the existing notebook on the input parameter `n_min_threshold` to show an example on our RTD page  ()

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [x] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [x] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

2022-12-06 17:17 UTC, snilsn requested changes
Very good work @JuliaKukulies, a great addition. I found one issue with sorting for the dictionary case and have a suggestion for that.

2022-12-06 17:35 UTC, JuliaKukulies commented on tobac/feature_detection.py
> +            sorted_dict = dict(sorted(n_min_threshold.items()))
Thanks for your review and suggestions @snilsn. Agreed, I will change these two things!

2022-12-07 09:01 UTC, snilsn commented on tobac/feature_detection.py
> +    elif isinstance(n_min_threshold, np.ndarray):
I think checking for dict, list or int would be the right way to go. 1d numpy array would work too, but then we would need to test the shape, and also that all entries are ints.

2022-12-08 20:11 UTC, JuliaKukulies commented on tobac/feature_detection.py
> +    elif isinstance(n_min_threshold, np.ndarray):
You are right. I kept it as it is and checking for dict, list, and int.

2023-01-23 18:49 UTC, freemansw1 approved these changes
Thanks @JuliaKukulies! I'm happy with this as-is. Feel free to merge when you're ready.

2023-01-24 17:18 UTC, JuliaKukulies commented
Thanks @freemansw1 and @snilsn for reviewing this PR!

2023-01-24 17:18 UTC, merged