Added more documentation for dealing with big datasets
tobac-project/tobac pull request #408
Opened 2024-02-16 22:32 UTC by freemansw1

Added more details to our documentation around dealing with big datasets, including a new example notebook of running feature detection in parallel.

With @RBhupi from tobathon February 2024

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? 
* [ ] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [x] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

2024-02-19 09:33 UTC, w-k-jones reviewed
Looks good. The only change I would suggest to the notebook is performing tracking to show that this needs to be performed on a single dataframe, but that it can be done without loading all spatial data into memory. The notebook isn't yet displayed in the docs, is that intended? And the failure of the jupyter notebooks CI can be fixed with the inclusion of dask in `example_requirements.txt`, which has been done in #334

2024-05-09 21:24 UTC, freemansw1 commented
I'm ready for a review!

2024-05-25 17:24 UTC, w-k-jones approved these changes
All looks good to me! Happy for this to be merged when ready

2024-05-31 08:23 UTC, fsenf requested changes
This is a nice addition. Thank you for your work!

I requested some formatting changes - which will be easy to do

2024-05-31 08:23 UTC, fsenf commented on doc/big_datasets_examples/index.rst
don't think that the index.rst is needed at all

2024-05-31 08:23 UTC, fsenf commented on doc/big_datasets_examples/notebooks/parallel_processing_tobac.ipynb
Please, resubmit this notebook after formatted with black!

2024-05-31 08:23 UTC, fsenf commented on doc/big_datasets.rst
> +   combined_dataframes= tobac.utils.general.combine_feature_dataframes(out_feature_dfs)
Please care that the code snippet is also formatted with black (maybe you copy it over once the notebook has been formatted,

2024-06-06 14:23 UTC, w-k-jones commented on doc/big_datasets_examples/notebooks/parallel_processing_tobac.ipynb
We should apply black formatting to all the notebooks at some point...

2024-07-18 18:22 UTC, freemansw1 commented on doc/big_datasets_examples/notebooks/parallel_processing_tobac.ipynb
I went ahead and formatted all of the notebooks with black while I was at it

2024-07-18 18:22 UTC, freemansw1 commented on doc/big_datasets_examples/index.rst
It was to display the way I had it, but I moved it to the notebook gallery instead.

2024-07-24 13:29 UTC, freemansw1 commented
Ok, @fsenf, I believe I've addressed your comments and I am now ready for a re-review.

2024-08-15 06:15 UTC, fsenf approved these changes
Thank you for update! I am happy with the changes. I especially like that the doc notebooks have been integrated into the example gallery: https://tobac--408.org.readthedocs.build/en/408/examples.html

Please go ahead and merge!

Cheers, Fabian.

PS: It would be cool to have nice looking thumbnails for the new gallery entry. I will create a new issue for that request.

2024-08-15 15:09 UTC, merged